CACHE_MODE: False
AOOD:
  MOTIF_ON: False
  ASGS:
    ENABLED: True  # 여기서 True로 덮어씌워야 ASGS 모델이 작동합니다.
  # novel-class
  OPEN_SET:
    WARM_UP: 20
    TH: 0.5 
    MOTIF_ON: False
    ALPHA: 0.01 
    KNN: 5 
    UNK_PROB: 0.5 
    MOTIF_LOSS_COEF: 0.1 
  # novel-scene
  CROSS_DOMAIN:
    MOTIF_ON: False
    BETA: 1.0 # std scaling 
DATASET:
  DA_MODE: source_only # 단일 도메인 학습
  AOOD_SETTING: 1 # Cityscapes -> Foggy Cityscapes 설정 (논문 참조)
  #AOOD_SCENE: 'cityscapes_to_foggy_cityscapes'
  #COCO_PANOPTIC_PATH: None
  COCO_PATH: '/data/datasets'
  # [중요] Unknown Class 개수 조절 (SOMA 로직 유지)
  # 3: Unknown 3개 평가 / 4: Unknown 4개 평가 / 5: Unknown 5개 평가
  AOOD_TASK: 3
  DATASET_FILE: cityscapes_to_foggycityscapes
  # [중요] NUM_CLASSES 설정 (Base 개수 + 1)
  # SOMA Setting 1의 Base Class는 3개이므로, 3 + 1 = 4로 설정
  NUM_CLASSES: 4 # base class 3 + unknown 1 = 4
  REMOVE_DIFFICULT: False

DEVICE: cuda
DIST:
  DISTRIBUTED: False
  DIST_BACKEND: nccl
  DIST_URL: env://
  GPU: 0
  RANK: 0
  WORLD_SIZE: 4
EVAL: False
LOSS:
  AUX_LOSS: True
  BACKBONE_LOSS_COEF: 0.1
  BBOX_LOSS_COEF: 5.0
  CHANNEL_QUERY_LOSS_COEF: 0.1
  CLS_LOSS_COEF: 2.0
  DA_GAMMA: 0
  DICE_LOSS_COEF: 1.0
  FOCAL_ALPHA: 0.25
  GIOU_LOSS_COEF: 2.0
  INSTANCE_QUERY_LOSS_COEF: 0.1
  MASK_LOSS_COEF: 1.0
  SET_COST_BBOX: 5.0
  SET_COST_CLASS: 2.0
  SET_COST_GIOU: 2.0
  SPACE_QUERY_LOSS_COEF: 0.1
MODEL:
  BACKBONE: resnet50
  BACKBONE_ALIGN: True
  CHANNEL_ALIGN: False
  DEC_LAYERS: 3
  DEC_N_POINTS: 4
  DILATION: False
  DIM_FEEDFORWARD: 1024
  DROPOUT: 0.1
  ENC_LAYERS: 3
  ENC_N_POINTS: 4
  FROZEN_WEIGHTS: None
  HIDDEN_DIM: 256
  INSTANCE_ALIGN: False
  MASKS: False
  NHEADS: 8
  NUM_FEATURE_LEVELS: 4
  NUM_QUERIES: 100
  POSITION_EMBEDDING: sine
  POSITION_EMBEDDING_SCALE: 6.283185307179586
  SPACE_ALIGN: False
  TWO_STAGE: False
  WITH_BOX_REFINE: False
NUM_WORKERS: 2
OUTPUT_DIR: ./outputs/table1
RESUME: 
LOAD_OPTIMIZER: False
SEED: 42 # This cannot strictly control the same results. Sorry, I do not know why.
START_EPOCH: 0
EVAL_EPOCH: 29
TRAIN:
  BATCH_SIZE: 6 # each gpu, 2 for source and 2 for target
  CLIP_MAX_NORM: 0.1
  EPOCHS: 65
  LR: 0.0002
  LR_BACKBONE: 2e-05
  LR_BACKBONE_NAMES: ['backbone.0']
  LR_DROP: 40
  LR_DROP_EPOCHS: None
  LR_LINEAR_PROJ_MULT: 0.1
  LR_LINEAR_PROJ_NAMES: ['reference_points', 'sampling_offsets']
  SGD: False
  WEIGHT_DECAY: 5e-4